language: node_js
node_js:
    - 11
install:
    - yarn install
script:
    - yarn build
    - cp index.html dist/ # TODO remove when vue-cli-plugin-vue-next has ts support, this is very hacky
    - sed -i 's/dist\/main.js/main.js/g' dist/index.html # TODO remove when vue-cli-plugin-vue-next has ts support, this is very hacky
    - echo 'vugel-example.planning.nl' > dist/CNAME
deploy:
    provider: pages
    skip_cleanup: true
    local_dir: dist
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master
